apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
  labels:
    app: my-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html
              subPath: website   # serve only the "website" folder
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          volumeMounts:
            - name: website-content
              mountPath: /tmp/git
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/Drkoen/my-website.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_WAIT
              value: "30"        # check for changes every 30s
            - name: GIT_SYNC_ONE_TIME
              value: "false"
            - name: GIT_SYNC_ROOT
              value: "/tmp/git"
            - name: GIT_SYNC_DEST
              value: "site"
      volumes:
        - name: website-content
          emptyDir: {}
